// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated automatically from the docs/ folder structure.
 * Each subfolder (tools, snippets, in-ontwikkeling) becomes a category via
 * its _category_.json file.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  toolsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
